// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Option struct {
	OptionID    int64  `json:"option_id"`
	OptionValue string `json:"option_value"`
	PollID      int64  `json:"poll_id"`
}

type Poll struct {
	PollID    int64     `json:"poll_id"`
	Question  string    `json:"question"`
	Owner     string    `json:"owner"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	Role              string    `json:"role"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	IsEmailVerified   bool      `json:"is_email_verified"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type Vote struct {
	VoteID   int64  `json:"vote_id"`
	OptionID int64  `json:"option_id"`
	Voter    string `json:"voter"`
}
