// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error)
	CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	GetOptions(ctx context.Context, pollID int64) ([]Option, error)
	GetPoll(ctx context.Context, pollID int64) (Poll, error)
	GetTotalVotes(ctx context.Context, pollID int64) ([]GetTotalVotesRow, error)
	GetUserByUserEmail(ctx context.Context, email string) (User, error)
	GetUserByUserName(ctx context.Context, username string) (User, error)
	GetVotesByPoll(ctx context.Context, arg GetVotesByPollParams) ([]GetVotesByPollRow, error)
	GetVotesByUser(ctx context.Context, arg GetVotesByUserParams) ([]Vote, error)
	ListPolls(ctx context.Context, arg ListPollsParams) ([]Poll, error)
}

var _ Querier = (*Queries)(nil)
